### ISSUE TITLE
Oracle JDK 7u75 download is failing

### ISSUE THREAD

**Issue by jbapple-cloudera** [awleblang/impala-setup#11]
```
[0mRecipe: java::oracle[0m
  * java_ark[jdk] action install
    * apt_package[curl] action install (up to date)
    [32m- download oracle tarball straight from the server[0m[2016-11-10T17:18:41+00:00] FATAL: Failed to extract file jdk-7u75-linux-x64.tar.gz!
[0m
    ================================================================================[0m
    [31mError executing action `install` on resource 'java_ark[jdk]'[0m
    ================================================================================[0m
    
[0m    SystemExit[0m
    ----------[0m
    exit[0m
    
[0m    Cookbook Trace:[0m
    ---------------[0m
    /mnt/expanse/impala-setup/cookbooks/java/providers/ark.rb:164:in `block (2 levels) in class_from_file'
[0m    /mnt/expanse/impala-setup/cookbooks/java/providers/ark.rb:142:in `block in class_from_file'[0m
    
[0m    Resource Declaration:[0m
    ---------------------[0m
    # In /mnt/expanse/impala-setup/cookbooks/java/recipes/oracle.rb
[0m    
[0m     53: java_ark "jdk" do
[0m     54:   url tarball_url
[0m     55:   default node['java']['set_default']
[0m     56:   checksum tarball_checksum
[0m     57:   app_home java_home
[0m     58:   bin_cmds bin_cmds
[0m     59:   alternatives_priority node['java']['alternatives_priority']
[0m     60:   retries node['java']['ark_retries']
[0m     61:   retry_delay node['java']['ark_retry_delay']
[0m     62:   connect_timeout node['java']['ark_timeout']
[0m     63:   action :install
[0m     64: end
[0m     65: 
[0m    
[0m    Compiled Resource:[0m
    ------------------[0m
    # Declared in /mnt/expanse/impala-setup/cookbooks/java/recipes/oracle.rb:53:in `from_file'
[0m    
[0m    java_ark("jdk") do
[0m      action [:install]
[0m      supports {:report=>true, :exception=>true}
[0m      retries 0
[0m      retry_delay 2
[0m      default_guard_interpreter :default
[0m      declared_type :java_ark
[0m      cookbook_name "java"
[0m      recipe_name "oracle"
[0m      url "http://download.oracle.com/otn-pub/java/jdk/7u75-b13/jdk-7u75-linux-x64.tar.gz"
[0m      default true
[0m      checksum "6f1f81030a34f7a9c987f8b68a24d139"
[0m      app_home "/usr/lib/jvm/java-7-oracle-amd64"
[0m      bin_cmds ["appletviewer", "apt", "ControlPanel", "extcheck", "idlj", "jar", "jarsigner", "java", "javac", "javadoc", "javafxpackager", "javah", "javap", "javaws", "jcmd", "jconsole", "jcontrol", "jdb", "jhat", "jinfo", "jmap", "jps", "jrunscript", "jsadebugd", "jstack", "jstat", "jstatd", "jvisualvm", "keytool", "native2ascii", "orbd", "pack200", "policytool", "rmic", "rmid", "rmiregistry", "schemagen", "serialver", "servertool", "tnameserv", "unpack200", "wsgen", "wsimport", "xjc"]
[0m      alternatives_priority 1062
[0m      connect_timeout 600
[0m      owner "root"
[0m    end
[0m    
[0m    Platform:[0m
    ---------[0m
    x86_64-linux[0m
    
[0m[0m
Running handlers:[0m
[2016-11-10T17:18:41+00:00] ERROR: Running exception handlers
Running handlers complete
[0m[2016-11-10T17:18:41+00:00] ERROR: Exception handlers complete
Chef Client failed.
```

**Comment by jbapple-cloudera** [comment]
When I try a wget at that location, I get a 503: Service Unavailable

**Comment by jbapple-cloudera** [comment]
This might be an Oracle problem, though - even when using the website to download the latest JVM (http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.tar.gz), I get a page telling me "Thank you for accessing the Oracle Software Delivery Cloud. Due to your country location, we are unable to process your request."

**Comment by jbapple-cloudera** [comment]
This is now working; it seems like it was a problem with the Oracle website.
